tools:
  exceptions:
    frontend: https://dcsil.sentry.io/projects/ezra-mvp-frontend/?project=4504776458698752
    backend: https://dcsil.sentry.io/projects/ezra-mvp-backend/?project=4504776538324992
  logging: https://logtail.com/team/150073/tail?s=242934
  ci: https://github.com/dcsil/ezraFitMVP/blob/main/.github/workflows/githubActionsNode.yml

services:
  production: 
    frontend: https://ezrafit-frontend.onrender.com/
    backend: https://ezrafit-backend-ayjn.onrender.com

docs:
  getting_started: https://github.com/dcsil/ezra

commands:
  bootstrap: ./scripts/bootstrap.sh
  database: https://console.firebase.google.com/u/0/project/ezrafit-e157e/database/ezrafit-e157/database
  server: 
    frontend: cd frontend; npm start
    backend: cd backend; source be/bin/activate; python3 app.py
  test: 
    frontend: cd frontend; npm test
    backend: python -m pytest
